#!/usr/bin/env python3

import os
import sys
import math
import random
import argparse
from datetime import datetime

import numpy
from PIL import Image
from wordcloud import WordCloud, ImageColorGenerator

_INSTALL_DIR = os.path.dirname(os.path.realpath(__file__))

_LOGOS = list(map(
    lambda l: os.path.splitext(l)[0],
    os.listdir(os.path.join(_INSTALL_DIR, 'logo'))
))

_MSG = set()
def _msg(**kwargs):
    if 'id' in kwargs:
        if kwargs['id'] in _MSG:
            return
        _MSG.add(kwargs['id'])
    if 'type' in kwargs and kwargs['type'] == 'err':
        print('Error: {text}'.format(text=kwargs['text']), file=sys.stderr)
        sys.exit(1)
    elif 'type' in kwargs and kwargs['type'] == 'warn':
        print('Warning: {text}'.format(text=kwargs['text']), file=sys.stderr)
    else:
        print('Info: {text}'.format(text=kwargs['text']))

def _getDefaultLogo():
    try:
        import distro
        dist = distro.id() # See https://distro.readthedocs.io/en/latest/#distro.id
        if dist in _LOGOS:
            return dist
        else:
            _msg(id='distro', text='No default logo for distribution \'{}\''.format(dist))
    except:
        _msg(id='distro', text='Could not auto-detect Linux distribution. Install the distro module.')
        pass
    return 'tux'

def _getDefaultOutputFile():
    return 'wordwall_' + datetime.now().strftime('%Y%m%d_%H%M%S') + '.png'

def _getDefaultRes():
    try:
        import Xlib.display
        res = Xlib.display.Display().screen().root.get_geometry()
        return [res.width, res.height]
    except:
        _msg(id='xlib', text='Could not auto-detect screen resolution. Install the Xlib module.')
        pass
    return [1920, 1080] # fallback

def _getMaxWords(res, args=None):
    if args and args.max_words:
        return args.max_words
    area = res[0] * res[1]
    return int(round(area / 1000, -2))

def _getFontSize(res, args=None):
    if args and args.font_size:
        return args.font_size
    return res[1] // 27

def _getText(args):
    text = ""
    # Find files
    files = []
    if args.text_file:
        files.extend(args.text_file)
    home = os.path.expanduser('~')
    if args.shell_history:
        for f in [
            os.path.join(home, '.bash_history'),
            os.path.join(home, '.history'),
            os.path.join(home, '.histfile'),
            os.path.join(home, '.zhistory'),
            os.path.join(home, '.zsh_history'),
            os.path.join(home, '.local', 'share', 'fish', 'fish_history')
        ]:
            if os.path.exists(f):
                files.append(f)
    if args.shell_init:
        for f in [
            os.path.join(home, '.bashrc'),
            os.path.join(home, '.bash_profile'),
            os.path.join(home, '.profile'),
            os.path.join(home, '.cshrc'),
            os.path.join(home, '.zshrc'),
            os.path.join(home, '.zshenv'),
            os.path.join(home, '.zprofile'),
            os.path.join(home, '.config', 'fish', 'config.fish')
        ]:
            if os.path.exists(f):
                files.append(f)
    if args.git_repo:
        try:
            import git
            for repo_path in args.git_repo:
                try:
                    repo = git.Repo(repo_path)
                    for commit in repo.iter_commits():
                        text += commit.message
                except:
                    _msg(type='warn', text='Not a git repository: {}'.format(repo_path))
                    pass
        except:
            _msg(id='git', type='warn', text='Cannot fetch git logs. Install the GitPython module.')
            pass

    # Concatenate text in all files
    for f in files:
        try:
            text += open(f, 'r').read()
        except:
            _msg(type='warn', text='Failed to read source file: {}'.format(f))
            pass
    return text

def _rgbReplace(img, src, dst):
    data = numpy.array(img.convert('RGBA'))
    r, g, b, a = data.T
    if len(src) == 4:
        pixels = (r == src[0]) & (g == src[1]) & (b == src[2]) & (a == src[3])
    else:
        pixels = (r == src[0]) & (g == src[1]) & (b == src[2])
    if len(dst) == 4:
        data[...][pixels.T] = dst
    else:
        data[..., :-1][pixels.T] = dst
    return Image.fromarray(data)

def _getMask(args):
    # Get mask file path
    if args.mask_file:
        mask_file = args.mask_file
    elif args.logo:
        mask_file = os.path.join(_INSTALL_DIR, 'logo', args.logo + '.png')
    # Determine canvas width/height
    if args.bg_image:
        width, height = Image.open(args.bg_image).size
    else:
        width = args.width
        height = args.height
    # Create canvas
    canvas = Image.new('RGBA', (width, height), color='#ffffff')
    # Resize logo
    logo_height = height // 2
    logo = Image.open(mask_file).convert("RGBA")
    logo = logo.resize((logo_height, logo_height))
    # Replace pure white FFFFFF with FEFEFE in the logo
    # to distinguish with the canvas (negative space)
    if args.mask_show_white:
        logo = _rgbReplace(logo, (255, 255, 255), (254, 254, 254))
    # Paste logo to center of canvas
    pos = (
        (width - logo_height) // 2,
        logo_height // 2
    )
    canvas.paste(logo, pos, logo)
    # Return image mask data
    return numpy.array(canvas), width, height

def _generate(args):
    text = _getText(args)
    if not text:
        _msg(type='err', text='No valid source text. Please check your arguments.')
    mask, width, height = _getMask(args)
    if args.bg_image and not args.bg_color:
        # Pasting a transparent overlay onto the background image can cause harsh edges
        # Match the RGB part of the sole foreground color if applicable to improve it
        if args.color and len(args.color) == 1:
            if len(args.color) == 7: # RGB
                bg_color = args.color[0] + '00'
            elif len(args.color) == 9: # RGBA
                bg_color = args.color[:-2] + '00'
            else:
                bg_color = '#77777700'
        else:
            _msg(id='bg_image', text='Background image works best with a single foreground color setting. There may be harsh edges on the text otherwise.')
            bg_color = '#77777700'
    else:
        bg_color = args.bg_color
    cloud = WordCloud(
        width=width,
        height=height,
        background_color=bg_color,
        max_words=_getMaxWords((width, height), args),
        mask=mask,
        font_path=args.font_path,
        max_font_size=_getFontSize((width, height), args),
        random_state=45,
        relative_scaling=0,
        mode="RGBA"
    ).generate(text)
    # Apply color function
    if args.color:
        color_func = lambda *a, **kw: random.choice(args.color)
    else:
        color_func = ImageColorGenerator(mask)
    cloud.recolor(color_func=color_func)
    if args.bg_image:
        overlay = Image.fromarray(cloud.to_array())
        bg_image = Image.open(args.bg_image).convert("RGBA")
        bg_image.paste(overlay, None, overlay)
        bg_image.save(args.output)
    else:
        cloud.to_file(args.output)

def main():
    # Parse arguments
    parser = argparse.ArgumentParser(description='Generates a word cloud wallpaper from user text files')
    # SOURCES
    group = parser.add_argument_group('SOURCES')
    group.add_argument('--shell-history', action='store_true', help='read shell history files')
    group.add_argument('--shell-init', action='store_true', help='read shell init files')
    group.add_argument('--git-repo', metavar='DIR', type=str, action='append', help='path to git repo(s) to read logs from (may be given multiple times)')
    group.add_argument('--text-file', metavar='FILE', type=str, action='append', help='read from text file(s) (may be given multiple times)')
    # APPEARANCE
    group = parser.add_argument_group('APPEARANCE')
    group.add_argument('--logo', type=str, default=_getDefaultLogo(), choices=_LOGOS, help='logo to use. Default: \'%(default)s\'')
    group.add_argument('--mask-file', type=str, help='mask file to use')
    group.add_argument('--mask-show-white', action='store_true', help='disable masking out pure white')
    group.add_argument('-W', '--width', type=int, default=_getDefaultRes()[0], help='output image width. Default: \'%(default)s\'')
    group.add_argument('-H', '--height', type=int, default=_getDefaultRes()[1], help='output image height. Default: \'%(default)s\'')
    group.add_argument('--max-words', type=int, help='max number of words to use. Default: \'{}\''.format(_getMaxWords(_getDefaultRes())))
    group.add_argument('--font-path', type=str, help='font path to use')
    group.add_argument('--font-size', type=int, help='mask file to use. Default: \'{}\''.format(_getFontSize(_getDefaultRes())))
    group.add_argument('--bg-color', metavar='COLOR', type=str, default='#000000', help='background color. Default: \'%(default)s\'')
    group.add_argument('--color', metavar='COLOR', type=str, action='append', help='foreground color(s) (may be given multiple times)')
    group.add_argument('--bg-image', metavar='FILE', type=str, help='background image to superimpose word cloud onto. Overrides width and height.')
    # Output
    parser.add_argument('output', metavar='FILE', type=str, nargs='?', default=_getDefaultOutputFile(), help='path to output file. Default: \'%(default)s\'')
    args = parser.parse_args()
    # Select default source if none is given
    if not args.shell_history and not args.shell_init and not args.git_repo and not args.text_file:
        args.shell_history = True
    # Generate wallpaper
    _generate(args)

if __name__ == '__main__':
    main()
